- docs/query.md
> Add edge query not supported info to docs.

- graphlearn/python/model/tf/ego_tensor.py
> fix typo: HopTenor-> HopTensor

- graphlearn/common/threading/sync/lock.h
- graphlearn/common/threading/this_thread.h
- graphlearn/common/threading/thread/test/thread_unittest.cpp
- graphlearn/core/graph/storage/types.h
Local validation on tests looks goods, but there are still some fs-related
failure, which, would be fixed in later PRs.
> Make the codebase compilable (and runnable) on Mac OS.

- graphlearn/core/graph/graph.h
- graphlearn/core/graph/graph_store.cc
- graphlearn/core/graph/heter_dispatcher.h
- graphlearn/core/graph/local_graph.cc
- graphlearn/core/graph/local_noder.cc
- graphlearn/core/graph/noder.h
- graphlearn/core/graph/remote_graph.cc
- graphlearn/core/graph/remote_noder.cc
- graphlearn/core/graph/storage/graph_storage.h
- graphlearn/core/graph/storage/node_storage.h
- graphlearn/core/graph/storage/vineyard_edge_storage.h
- graphlearn/core/graph/storage/vineyard_graph_storage.h
- graphlearn/core/graph/storage/vineyard_node_storage.h
- graphlearn/core/graph/storage/vineyard_storage_utils.cc
- graphlearn/core/graph/storage/vineyard_storage_utils.h
- graphlearn/core/graph/storage/vineyard_topo_storage.h
- graphlearn/core/graph/storage_creator.cc
- graphlearn/core/graph/storage_creator.h
- graphlearn/include/data_source.h
- graphlearn/python/graph.py
- graphlearn/python/py_export.cc
Syntax:
```python
def local_training(handle, config):
g = gl.Graph().vineyard(handle) \
.node_attributes("person", ["attr-0"], 0, 1, 0) \
.node_view("train", "person", nsplit=4, split_range=(2, 4)) \
.init_vineyard(standalone=True)
nodes = g.V("train").batch(4).emit()
print(nodes.ids)
print(nodes.int_attrs)
print(nodes.float_attrs)
```
> Implements attribute selector.

- CMakeLists.txt
- examples/__init__.py
- graphlearn/python/model/tf/ego_flow.py
- raise import error when import examples (like no tensorflow found)
- fix python3 not has next function
> Fixes the `.next()` on iterator with python 3, and optimized the dependency find process in CMakeLists.txt

- graphlearn/service/dist/channel_manager.cc
- graphlearn/service/dist/grpc_channel.cc
- graphlearn/service/dist/grpc_channel.h
> stop the channel_manager only when all channels stoped

- graphlearn/service/dist/channel_manager.cc
- graphlearn/service/dist/grpc_channel.cc
- graphlearn/service/dist/grpc_channel.h
> fix: absence of a colon and typo

- graphlearn/python/model/tf/trainer.py
Signed-off-by: Tao He <sighingnow@gmail.com>
> Use MonitoredTrainingSession to support checkpointing.

- CMakeLists.txt
- graphlearn/common/base/log.cc
Signed-off-by: Tao He <sighingnow@gmail.com>
> Avoid initialize glog twice when issuing multiple runs.

- examples/tf/gat/gat.py
- examples/tf/gcn/gcn.py
Related issue: https://github.com/alibaba/GraphScope/issues/1413
> Set a reasonable neighbs_num as default value for gcn and gat

- examples/tf/bipartite_graphsage/bipartite_graph_sage.py
Related issue: https://github.com/alibaba/GraphScope/issues/1497
> Fix bipartite_graph_sage get node embedding bug

- graphlearn/examples/pytorch/gcn/gcn.py
fix gcn bug
解决issue#230的bug：https://github.com/alibaba/graph-learn/issues/230
> fix out_dim in pytorch GCN example.

- graphlearn/examples/tf/ego_sage/README.md
- graphlearn/examples/tf/ego_sage/ego_sage_data_loader.py
- graphlearn/examples/tf/ego_sage/k8s/README.md
- graphlearn/examples/tf/ego_sage/k8s/dist.yaml
- graphlearn/examples/tf/ego_sage/k8s/dist_train.py
- graphlearn/examples/tf/ego_sage/train_supervised.py
- graphlearn/examples/tf/ego_sage/train_unsupervised.py
1. Fix k8s tests in examples
2. Update test docs
> Fix k8s tests in examples

- graphlearn/python/nn/dataset.py
- graphlearn/python/nn/tf/data/dataset.py
> gl: fix numpy compatibility of inhomogeneous arrays

- graphlearn/python/graph.py
> Add timestamp field for vineyard decoder

- graphlearn/examples/tf/ego_gcn_vineyard/README.md
- graphlearn/examples/tf/ego_gcn_vineyard/__init__.py
- graphlearn/examples/tf/ego_gcn_vineyard/graph.json
- graphlearn/examples/tf/ego_gcn_vineyard/train_supervised.py
> Add an end-to-end example about training over vineyard graphs

- graphlearn/CMakeLists.txt
- graphlearn/setup/setup.py
To keep compatibility with latest grpc/protobuf.
> Respect the inferred `GL_CXX_DIALECT` in setup.py as well.

- graphlearn/python/graph.py
> Fix: assign value for dag root when GSL starts from edge

- dynamic_graph_service/src/service/event_handler.cc
> Allow the vertex ID in serving request to be int64

- graphlearn/CMakeLists.txt
> fix: find protobuf with CONFIG to correctly build in macos 12

- graphlearn/CMakeLists.txt
> Fix: differentiate how protobuf is found in mac and linux
